function renderSheet(){
  const root=document.getElementById('sheet-root');
  if(!ui.sheet){root.innerHTML='';return}
  root.innerHTML=`<div class="sheet-layer"><button class="sheet-backdrop" data-action="close-sheet" aria-label="Schließen"></button><section class="sheet"><div class="sheet-handle"></div>${sheetContent()}</section></div>`;
}
function sheetHeader(title,subtitle=''){return `<div class="sheet-header"><div><h2>${esc(title)}</h2>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div><button class="sheet-close" data-action="close-sheet">×</button></div>`}
function field(label,control){return `<label class="field"><span>${esc(label)}</span>${control}</label>`}
function amountInput(){return `<div class="amount-input"><input name="amount" inputmode="decimal" placeholder="0,00" autofocus><span>€</span></div>`}
function options(items,selected=''){return items.map(x=>`<option ${x===selected?'selected':''}>${esc(x)}</option>`).join('')}

function sheetContent(){
  switch(ui.sheet){
    case 'quick':return `${sheetHeader('Hinzufügen')}<div class="quick-grid">
      <button data-action="new-expense"><span>💸</span><strong>Ausgabe</strong></button><button data-action="new-income"><span>💰</span><strong>Einnahme</strong></button><button data-action="saving-first" ${!data.goals.length?'disabled':''}><span>🎯</span><strong>Sparen</strong></button><button data-action="new-fuel" ${!data.car?'disabled':''}><span>⛽</span><strong>Tanken</strong></button><button data-action="new-car-expense" ${!data.car?'disabled':''}><span>🚗</span><strong>Autokosten</strong></button><button data-action="new-mood"><span>🙂</span><strong>Stimmung</strong></button><button data-action="new-remember"><span>🧠</span><strong>Merken</strong></button></div>`;
    case 'transaction':{const type=ui.transactionType,cats=type==='expense'?expenseCategories:incomeCategories;return `${sheetHeader(type==='expense'?'Ausgabe':'Einnahme')}<form data-form="transaction">${amountInput()}${field('Kategorie',`<select name="category">${options(cats)}</select>`)}${field('Beschreibung',`<input name="note" placeholder="${type==='expense'?'z. B. Mittagessen':'optional'}">`)}${field('Datum',`<input name="date" type="date" value="${todayISO()}">`)}<button class="sheet-save">Speichern</button></form>`}
    case 'goal':return `${sheetHeader('Neues Sparziel','Ein Ziel, ein Betrag. Mehr braucht es nicht.')}<form data-form="goal"><div class="emoji-name"><input name="emoji" class="emoji-input" value="🎯" maxlength="2"><input name="name" placeholder="z. B. Neues Auto" autofocus></div>${field('Zielbetrag',`<input name="target" inputmode="decimal" placeholder="10.000 €">`)}${field('Schon gespart',`<input name="current" inputmode="decimal" placeholder="0 €">`)}${field('Monatliche Sparrate (optional)',`<input name="monthly" inputmode="decimal" placeholder="500 €">`)}<button class="sheet-save">Sparziel erstellen</button></form>`;
    case 'saving':{if(!data.goals.length)return `${sheetHeader('Sparen')}<p class="sheet-note">Lege zuerst ein Sparziel an.</p>`;const goal=data.goals.find(g=>g.id===ui.goalId)||data.goals[0];return `${sheetHeader(goal.name,`${money(goal.currentAmount)} von ${money(goal.targetAmount)}`)}<form data-form="saving"><input type="hidden" name="goalId" value="${goal.id}">${data.goals.length>1?field('Sparziel',`<select name="goalIdSelect">${data.goals.map(g=>`<option value="${g.id}" ${g.id===goal.id?'selected':''}>${esc(g.emoji)} ${esc(g.name)}</option>`).join('')}</select>`):''}<div class="segmented"><button type="button" class="active" data-action="saving-type" data-value="deposit">Einzahlen</button><button type="button" data-action="saving-type" data-value="withdrawal">Entnehmen</button></div><input type="hidden" name="type" value="deposit">${amountInput()}${field('Notiz (optional)',`<input name="note" placeholder="z. B. August">`)}<button class="sheet-save">Speichern</button></form>`}
    case 'car-setup':{const c=data.car||{};return `${sheetHeader(data.car?'Auto bearbeiten':'Auto einrichten')}<form data-form="car">${field('Marke',`<input name="make" value="${esc(c.make||'')}" placeholder="Citroën" autofocus>`)}${field('Modell',`<input name="model" value="${esc(c.model||'')}" placeholder="C3">`)}${field('Kennzeichen (optional)',`<input name="plate" value="${esc(c.plate||'')}" placeholder="BT · YA 123">`)}${field('Kilometerstand',`<input name="odometer" inputmode="numeric" value="${c.odometer||''}" placeholder="37250">`)}<button class="sheet-save">Speichern</button></form>`}
    case 'fuel':{const odo=data.car?.odometer||data.fuelEntries[0]?.odometer||'';return `${sheetHeader('Tanken')}<form data-form="fuel">${field('Kilometerstand',`<input name="odometer" inputmode="numeric" value="${odo}" autofocus>`)}<div class="two-fields">${field('Liter',`<input name="liters" inputmode="decimal" placeholder="42.5">`)}${field('Gesamtpreis',`<input name="total" inputmode="decimal" placeholder="72.30">`)}</div>${field('Tankstelle (optional)',`<input name="station" placeholder="Aral">`)}<label class="switch-row"><span>Vollgetankt</span><input name="full" type="checkbox" checked></label><button class="sheet-save">Tankvorgang speichern</button></form>`}
    case 'car-expense':return `${sheetHeader('Autokosten')}<form data-form="car-expense">${amountInput()}${field('Kategorie',`<select name="category">${options(['Versicherung','Steuer','Reparatur','Service','Reifen','Waschanlage','Parken','Maut','TÜV','Zubehör','Sonstiges'],'Service')}</select>`)}${field('Beschreibung',`<input name="note" placeholder="optional">`)}<button class="sheet-save">Speichern</button></form>`;
    case 'reminder':return `${sheetHeader('Erinnerung','Datum oder Kilometer reicht.')}<form data-form="reminder">${field('Was?',`<input name="title" value="TÜV" autofocus>`)}${field('Fällig am',`<input name="dueDate" type="date">`)}<div class="or">oder</div>${field('Fällig bei km',`<input name="dueOdometer" inputmode="numeric" placeholder="40000">`)}<button class="sheet-save">Erinnerung speichern</button></form>`;
    case 'mood':{const m=data.moods.find(x=>x.date===todayISO())||{mood:4,energy:7,stress:3};return `${sheetHeader('Wie war dein Tag?')}<form data-form="mood"><input type="hidden" name="mood" value="${m.mood}"><div class="mood-picker">${[1,2,3,4,5].map(v=>`<button type="button" class="${Number(m.mood)===v?'selected':''}" data-action="pick-mood" data-value="${v}">${moodEmoji[v]}</button>`).join('')}</div>${field('Schlaf in Stunden',`<input name="sleep" inputmode="decimal" value="${m.sleepHours??''}" placeholder="7.5">`)}<label class="range-field"><span><b>Energie</b><em id="energy-value">${m.energy||7}/10</em></span><input name="energy" type="range" min="1" max="10" value="${m.energy||7}"></label><label class="range-field"><span><b>Stress</b><em id="stress-value">${m.stress||3}/10</em></span><input name="stress" type="range" min="1" max="10" value="${m.stress||3}"></label>${field('Ein Satz zum Tag (optional)',`<textarea name="note" rows="3" placeholder="Was war heute wichtig?">${esc(m.note||'')}</textarea>`)}<button class="sheet-save">Tag speichern</button></form>`}
    case 'remember':return `${sheetHeader('Merken')}<form data-form="remember">${field('Was möchtest du nicht vergessen?',`<textarea name="text" rows="4" placeholder="Film anschauen, Mama fragen, Restaurant besuchen …" autofocus></textarea>`)}<input type="hidden" name="category" value="Gedanke"><div class="chip-list">${rememberCategories.map(c=>`<button type="button" class="${c==='Gedanke'?'active':''}" data-action="pick-category" data-value="${c}">${rememberEmoji[c]} ${c}</button>`).join('')}</div><button class="sheet-save">Merken</button></form>`;
    case 'settings':return `${sheetHeader('Einstellungen')}<form data-form="settings">${field('Dein Name (optional)',`<input name="name" value="${esc(data.settings.name||'')}" placeholder="Yazen">`)}${field('Monatsbudget',`<input name="budget" inputmode="decimal" value="${data.settings.monthlyBudget}">`)}<button class="sheet-save">Speichern</button></form><div class="settings-actions"><button data-action="install-help">📱 Auf Home-Bildschirm installieren</button><button data-action="export-data">↗ Daten als JSON sichern</button><button data-action="import-data">↙ Backup importieren</button><button class="danger-text" data-action="reset-data">Alle lokalen Daten löschen</button></div><p class="privacy-note">Deine Daten verlassen dieses Gerät nicht. Es gibt kein Konto und keinen Server.</p>`;
    case 'install':return `${sheetHeader('Als App installieren')}<div class="install-steps"><div><span>1</span><p>Öffne diese Seite in <strong>Safari</strong>.</p></div><div><span>2</span><p>Tippe unten auf <strong>Teilen</strong> ⤴︎.</p></div><div><span>3</span><p>Wähle <strong>„Zum Home-Bildschirm“</strong>.</p></div><div><span>4</span><p>Aktiviere <strong>„Als Web-App öffnen“</strong> und tippe auf Hinzufügen.</p></div></div><p class="sheet-note">Danach startet Alltag mit eigenem Icon und ohne Safari-Leiste.</p>`;
    default:return '';
  }
}